# Generated by Django 4.2.19 on 2025-07-17 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_buildingfloor_name_de_buildingfloor_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndoorFingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address.', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')], verbose_name='BSSID')),
                ('fp_id', models.IntegerField(blank=True, max_length=150, null=True, verbose_name='Fingerprint ID')),
                ('room_external_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Room external ID')),
                ('site_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Site ID')),
                ('rssi', models.FloatField(blank=True, null=True, verbose_name='Received Signal Strength Indicator')),
                ('floor_num', models.FloatField(blank=True, null=True, verbose_name='Floor number')),
            ],
            options={
                'ordering': ['fp_id', 'bssid'],
            },
        ),
    ]
